name: analytics-service-ci

on:
  push:
    branches:
      - main
    paths:
      - app/analytics-service/**
      - .github/workflows/analytics-service-ci.yml
  pull_request:
    # Paths removido. O filtro é feito pelo job 'detect-changes'.

permissions:
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: devsecops-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            should_run:
              - 'app/analytics-service/**'
              - '.github/workflows/analytics-service-ci.yml'

  validate:
    needs: detect-changes
    if: github.event_name != 'pull_request' || needs.detect-changes.outputs.should_run == 'true'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/validate.yml@1b2363c696638110ad28641f217631dac79e50a1
    with:
      service-name: analytics-service
      service-language: python
      service-path: app/analytics-service

  security:
    needs: validate
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/security.yml@1b2363c696638110ad28641f217631dac79e50a1
    with:
      service-name: analytics-service
      service-language: python
      service-path: app/analytics-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  image-pr:
    needs: security
    if: github.event_name == 'pull_request'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@1b2363c696638110ad28641f217631dac79e50a1
    with:
      service-name: analytics-service
      service-dockerfile: app/analytics-service/Dockerfile
      service-path: app/analytics-service
      image-tag: pr-${{ github.event.pull_request.number }}
      push-images: false

  image-dev:
    needs: security
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@1b2363c696638110ad28641f217631dac79e50a1
    with:
      service-name: analytics-service
      service-dockerfile: app/analytics-service/Dockerfile
      service-path: app/analytics-service
      ecr-repository-prefix: togglemaster-dev
      image-tag: v0.${{ github.run_number }}.0
      push-images: true
      environment: dev

  promote-dev:
    needs: image-dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.image-dev.result == 'success'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/update-gitops.yml@1b2363c696638110ad28641f217631dac79e50a1
    with:
      service-name: analytics-service
      gitops-values-file: environments/dev/apps/analytics-values.yaml
      gitops-repo: jhouzera/togglemaster-gitops
      image-repository: ${{ needs.image-dev.outputs.image-repository }}
      image-tag: ${{ needs.image-dev.outputs.image-tag }}
      image-digest: ${{ needs.image-dev.outputs.image-digest }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      GITOPS_REPO: ${{ secrets.GITOPS_REPO }}

