name: analytics-service-ci

on:
  push:
    branches:
      - develop
    paths:
      - app/analytics-service/**
      - .github/workflows/analytics-service-ci.yml
  pull_request:
    paths:
      - app/analytics-service/**
      - .github/workflows/analytics-service-ci.yml

permissions:
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: devsecops-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/validate.yml@main
    with:
      service-name: analytics-service
      service-language: python
      service-path: app/analytics-service

  security:
    needs: validate
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/security.yml@main
    with:
      service-name: analytics-service
      service-language: python
      service-path: app/analytics-service
    secrets: inherit

  image-pr:
    needs: security
    if: github.event_name == 'pull_request'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@main
    with:
      service-name: analytics-service
      service-dockerfile: app/analytics-service/Dockerfile
      service-path: app/analytics-service
      image-tag: pr-${{ github.event.pull_request.number }}
      push-images: false

  image-dev:
    needs: security
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@main
    with:
      service-name: analytics-service
      service-dockerfile: app/analytics-service/Dockerfile
      service-path: app/analytics-service
      ecr-repository-prefix: togglemaster-dev
      image-tag: v0.${{ github.run_number }}.0
      push-images: true
      environment: dev

