name: auth-service-ci

on:
  push:
    branches:
      - main
    paths:
      - app/auth-service/**
      - .github/workflows/auth-service-ci.yml
  pull_request:
    # Paths removido. O filtro é feito pelo job 'detect-changes'.

concurrency:
  group: devsecops-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.should_run }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3
        id: filter
        with:
          filters: |
            should_run:
              - 'app/auth-service/**'
              - '.github/workflows/auth-service-ci.yml'

  validate:
    permissions:
      contents: read
    needs: detect-changes
    if: github.event_name == 'pull_request' && needs.detect-changes.outputs.should_run == 'true'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/validate.yml@f2fd28e16c3dab1958ba25f42fb6bd3c78e7ea8a
    with:
      service-name: auth-service
      service-language: go
      service-path: app/auth-service

  security:
    permissions:
      contents: read
      security-events: write
    needs: validate
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/security.yml@f2fd28e16c3dab1958ba25f42fb6bd3c78e7ea8a
    with:
      service-name: auth-service
      service-language: go
      service-path: app/auth-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  image-pr:
    permissions:
      contents: read
      id-token: write
    needs: security
    if: github.event_name == 'pull_request'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@f2fd28e16c3dab1958ba25f42fb6bd3c78e7ea8a
    with:
      service-name: auth-service
      service-dockerfile: app/auth-service/Dockerfile
      service-path: app/auth-service
      image-tag: pr-${{ github.event.pull_request.number }}
      push-images: false

  image-dev:
    permissions:
      contents: read
      id-token: write
    needs: detect-changes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@f2fd28e16c3dab1958ba25f42fb6bd3c78e7ea8a
    with:
      service-name: auth-service
      service-dockerfile: app/auth-service/Dockerfile
      service-path: app/auth-service
      ecr-repository-prefix: togglemaster-dev
      image-tag: v0.${{ github.run_number }}.0
      push-images: true
      environment: dev

  promote-dev:
    permissions:
      contents: read
    needs: image-dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.image-dev.result == 'success'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/update-gitops.yml@f2fd28e16c3dab1958ba25f42fb6bd3c78e7ea8a
    with:
      service-name: auth-service
      gitops-values-file: environments/dev/apps/auth-values.yaml
      gitops-repo: jhouzera/togglemaster-gitops
      image-repository: ${{ needs.image-dev.outputs.image-repository }}
      image-tag: ${{ needs.image-dev.outputs.image-tag }}
      image-digest: ${{ needs.image-dev.outputs.image-digest }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      GITOPS_REPO: ${{ secrets.GITOPS_REPO }}


