name: auth-service-ci

on:
  push:
    branches:
      - develop
      - main
    paths:
      - app/auth-service/**
      - .github/workflows/auth-service-ci.yml
  pull_request:
    paths:
      - app/auth-service/**
      - .github/workflows/auth-service-ci.yml

permissions:
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: devsecops-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/validate.yml@d35c49c659844bdfa952844acfc699bcf525b97c
    with:
      service-name: auth-service
      service-language: go
      service-path: app/auth-service

  security:
    needs: validate
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/security.yml@d35c49c659844bdfa952844acfc699bcf525b97c
    with:
      service-name: auth-service
      service-language: go
      service-path: app/auth-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  image-pr:
    needs: security
    if: github.event_name == 'pull_request'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@d35c49c659844bdfa952844acfc699bcf525b97c
    with:
      service-name: auth-service
      service-dockerfile: app/auth-service/Dockerfile
      service-path: app/auth-service
      image-tag: pr-${{ github.event.pull_request.number }}
      push-images: false

  image-dev:
    needs: security
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@d35c49c659844bdfa952844acfc699bcf525b97c
    with:
      service-name: auth-service
      service-dockerfile: app/auth-service/Dockerfile
      service-path: app/auth-service
      ecr-repository-prefix: togglemaster-dev
      image-tag: v0.${{ github.run_number }}.0
      push-images: true
      environment: dev

  promote-dev:
    needs: image-dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop' && needs.image-dev.result == 'success'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/update-gitops.yml@d35c49c659844bdfa952844acfc699bcf525b97c
    with:
      service-name: auth-service
      gitops-values-file: environments/dev/apps/auth-values.yaml
      gitops-repo: jhouzera/togglemaster-gitops
      image-repository: ${{ needs.image-dev.outputs.image-repository }}
      image-tag: ${{ needs.image-dev.outputs.image-tag }}
      image-digest: ${{ needs.image-dev.outputs.image-digest }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      GITOPS_REPO: ${{ secrets.GITOPS_REPO }}


