name: auto-pr

on:
  push:
    branches:
      - 'feat/**'
      - 'bug/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-pr:
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/auto-pr.yml@1c959936aa809bf82e34f93845a3edaa22de5cc5
    with:
      target-branch: develop
