name: auto-pr

on:
  push:
    branches:
      - 'feat/**'
      - 'bug/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-pr:
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/auto-pr.yml@f2e7727feb345648f788f4e927d4bcb59ff8ec16
    with:
      target-branch: develop
