name: auto-pr

on:
  push:
    branches:
      - 'feat/**'
      - 'bug/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-pr:
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/auto-pr.yml@d35c49c659844bdfa952844acfc699bcf525b97c
    with:
      target-branch: develop
