name: targeting-service-ci

on:
  push:
    branches:
      - develop
    paths:
      - app/targeting-service/**
      - .github/workflows/targeting-service-ci.yml
  pull_request:
    paths:
      - app/targeting-service/**
      - .github/workflows/targeting-service-ci.yml

permissions:
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: devsecops-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/validate.yml@main
    with:
      service-name: targeting-service
      service-language: python
      service-path: app/targeting-service

  security:
    needs: validate
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/security.yml@main
    with:
      service-name: targeting-service
      service-language: python
      service-path: app/targeting-service
    secrets: inherit

  image-pr:
    needs: security
    if: github.event_name == 'pull_request'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@main
    with:
      service-name: targeting-service
      service-dockerfile: app/targeting-service/Dockerfile
      service-path: app/targeting-service
      image-tag: pr-${{ github.event.pull_request.number }}
      push-images: false

  image-dev:
    needs: security
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/image.yml@main
    with:
      service-name: targeting-service
      service-dockerfile: app/targeting-service/Dockerfile
      service-path: app/targeting-service
      ecr-repository-prefix: togglemaster-dev
      image-tag: v0.${{ github.run_number }}.0
      push-images: true
      environment: dev

  promote-dev:
    needs: image-dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop' && needs.image-dev.result == 'success'
    uses: jhouzera/togglemaster-cicd-templates/.github/workflows/update-gitops.yml@b16d2601a6b948e2fb26f3772276581f31daa7cd
    with:
      service-name: targeting-service
      gitops-values-file: environments/dev/apps/targeting-values.yaml
      image-repository: ${{ needs.image-dev.outputs.image-repository }}
      image-tag: ${{ needs.image-dev.outputs.image-tag }}
      image-digest: ${{ needs.image-dev.outputs.image-digest }}
    secrets: inherit

